name: Run Tests and Generate Allure Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v22.13.1"

      - name: Install dependencies
        run: npm install

      - name: Clean old Allure results
        run: rm -rf allure-results allure-report

      - name: Download APK from Dropbox
        run: |
          file_url="https://www.dropbox.com/scl/fi/tlyh1lfaz0dgo4t0jrmgd/Android-NativeDemoApp-0.4.0.apk?rlkey=g6saust1jj9pi62ed1trzp2de&st=36shp57i&dl=1"
          file_name="app.apk"
          curl -L -o ${file_name} "${file_url}"

      - name: Upload APK to BrowserStack and get app_url
        id: upload_apk
        run:  
         curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" \
         -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
         -F "file=@app.apk" \
         -F "custom_id=android_demo_app"

      - name: Run tests
        run: npm run test

      - name: Generate Allure Report
        run: npm run report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: reports
          commit_message: deploy allure report

